apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GFZ1BBsvU0Fh6+jZM/e4tAiM5EZqk8YLH8tOSErYUHIp2O6A,iv:4YNjPLJSMo4WjwO8P+t1Jt6q0J1iQGdnoUfaBr5JjUE=,tag:G4CX+IYxafhtdJQDc49BHw==,type:str]
    credentials.json: ENC[AES256_GCM,data:LGAL3LBLZY7q4m8L7E7vJVwoUFURXAXL86VPsJNEY5C0kmgR6Q28lg+nrqhX3kdNcghqXPXvZFPvJ6/jOHIHn+Dbhgm8chFtAH2jzs8GM8HGa3avtx3/8XBuQ3J1/m1y5FJZbndi+4sa2rxqAksDsiY39Nwi0rQkDuybCjesWYQ1uHTzWg0XL2bZ3fHnePxosFSODRyRAjfnatA1MREX1okmoq9wSNWsc95UgkyZWQ==,iv:0fdWB2SNEVsMiqh1FOZMkKdAevHH9BRL/lPMpeLe1L4=,tag:jitYdJU4OzZFdAcXUdo0aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dUl1MWJtZ2pVTmhlYy9P
            L1hHQkFsdFFlcWNxL1JWSFc5U2djOXVaZ0VJCmhtUlQzL3N3WFl4dVA0M2pMS1F0
            a0phMzNzVkdIS3VWMFRZMERDSXE2RDAKLS0tIGZuUjhsbnRxZElJSFFkMWxrbDFY
            UGZDSjcvbUNwaUNwOUdTaytxUXVEdVUK+da7CxeYP0+NhvRxXxu2eeV39/kpgEnS
            gBoDeK0ZbzmxYRLe6zb4gGvVNGmZnXx9uvQkCp5tVHZSPQzLHH691g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T20:08:12Z"
    mac: ENC[AES256_GCM,data:yaTMp7Z4RcZrRxcUtkNbuW5YUCEr0b1WmJ4s4/MA3RvHl6ogFhcl8mVaTHP7+NzFnAcI6TxfVSDB7mFUlDb9llaOusRaagd11wlPmyZdMhJrqP5Ahu6aTT+bKwV+dQQDJxKR4uZMeyxP6nNeB1YfR48ZMjJ85HgmAaj+22O1QCc=,iv:IDLL0ZHD7mYsCOkaRel+icSpAlyK7uxW1KcFJwdLAgw=,tag:55bkM5uJfEdoumSJ75oKHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
