apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:al7fqGyATa+YlVlRrW5NofTj5bX7/Z2p2FYmjgALU+9E/AtSWTby3A==,iv:TlVwkuD5vd2yyjttDJirWgmfd50H8nYWhWUXGT8tC+o=,tag:fNdCC1/1CUF4T29HuedWIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ1lOempoeE0xYTU3alhz
            N1NzV3hZS2xaQm9jQmx0V3BHdzd4ZGZyTXdzCmtTTGp0T2pJVTlBVy81RlVGQW45
            VENwK0lZUUlwZ0Fpejg2S0JVYUZrK2sKLS0tIElhZFhYVTZ3ZTdOVkM5RWc0VFBy
            d1VuRU5rdmdGUFlBdEpkWkF1Zldza3MKa4XyxF+rfk1UgWCzvJktAiGilCE95gTy
            Sbt74P/Kdoe3uhZJ60/4+hM1D+8Irook99XkWH9uF+SXKIROj5JUQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T20:08:12Z"
    mac: ENC[AES256_GCM,data:LS4TWgT8VRrOGWwCuN6n1nttLbWiJKtyMXnERwlDsqCtHL2ZDm8nn5NVrH7wjNVr+ojnGODQHRqJ53zlxHjtP/M9ce6TpdWaX4p4jeVe9s74FsiQlF6TM3bI+ODATcXHPhOrLN0qQqCNIrodAfSX0IKk+fE2LaffU+xFBy4PL5U=,iv:eaSvYtH0aS0T+DGvNkr5PlSizeHof0MkeLJsE9dU5HQ=,tag:jNG2aC9lTyQcLYNi3iCGYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
