apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rEmCICIEuzz5zw==,iv:EKr4lfmvyBAjsQHNjow62vaAtK8B+td7011HvjFXf5o=,tag:bH4hogivFg9NSZvF4pNIXA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/GYRjxWKdtYZ51JyHUV9pQ==,iv:4GB20J0QTbEmnXvtFH/7g5IlUQw7znkBd69vE9XcxZQ=,tag:Csx+Huid6/L34l7M0uaLUg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VQP6fpJC+avLyVd61Z+7OP5wkZG669IYNvFw3Wbzvvd7zuFB,iv:nyq1Y1b7FzZ/ic9++CZPAblQrYsp/C3O70GvTteSJ10=,tag:wbaVf8kwb47M0GW7FxnzLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZllwQVdmV2tDL1lyT282
            WFJmcDlMUTNFb0h0d3hJWXIwbGt2V09ybmlNClh4NDFWcUxIdHR0cDdsZm1pQmgx
            aUpNNkwxeXUyUGplZlZrMURoSG9ncGMKLS0tIGNuY2lNOFgyYkMzVFpTbld4YVZh
            cmRpS0VVWVpmMGNnTjlONktUcTdvV1kK8YI5Q10LCce2UhORCuA8FORs0QgfoBxa
            87tQP5lR7306qZjCSTYKDZYQQTczqDi1cKHVmKEFJtkmKl0xCshdrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-28T21:04:35Z"
    mac: ENC[AES256_GCM,data:924BCS09qeATELprVwqolIDgJMwG5DATxvlwi3IpcT9Vaj4C/nv4Rc3KwfYbyfV2e/OsvUsH9U/7mmpkLC4U/tyz2Bp935/9HX52UrvZGMOGqL0+ucAia8E6BPx4bDjvpW+JSFHxI13KkdwBCLH7/g1upmIKLKF+Sf+P2kZEBu8=,iv:dL2fT9yyLPD5kNY8zpcd/2Db4K7tR5sxBpbkSBdB8Wk=,tag:lH6IdXSOMlqsFTYa8inLlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
