apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pa/v3jc7wgROdqNKC1Q=,iv:Uq7O1J9KDEOGkslXM7UrQu8rZ/wHUx5HjxPBx3QBofw=,tag:XK/Yk2vdQP1pfP8FftV0QQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mrp0ExnGV70qGElw6ejNSw==,iv:CtJw2ZklgzftJ8FaiPxxoKi59TPDl+Rx23XTq0e3jrw=,tag:emHXrmyKiHRhD7jMC/idjQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:qFVFXVVolyqwSd7v9RhOP4c/+KSY8PcaPZklMa/yQfZiNDpP,iv:8jKHlYZ0bBZ1GcYz/7oAD9du9Qi8gGeCPY4V6Iw52O4=,tag:J5DFNSksxkoAF647yZE9bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbjFONThYNWxMQXh5VnVJ
            cVlRaDZxWWJwWnNYeXhnNTk1dmdNWG52Y0IwCjFJbGJsSHVZUTZlVEk1QVB4VmxZ
            SVBjYUY0ZW9xSXBOeVdRTUlPK0RZbk0KLS0tIFREenZFeHZGSXNMUTRlNU1pVW9q
            cGxPK0gyNXlkWUY4SzRORC9DcFV1alEKcekqMP+2JkRmAirFtzjiYwaTlTfdDPDR
            4nQX3vK4JAOb8v0r1JmEtGdsTY+5lRORylWPWcLkjRSXaIvH9SXlQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T14:33:38Z"
    mac: ENC[AES256_GCM,data:D/nLdjtnM/BIEmfFs+dSftouxl2CJEkVNtlSHbk1/23ymTy6K4soq9rmtqaihu9aRYnLDexIa7kOni/1hX1o0yrqbIptFi0HUnvCOrHZ9r4ihcozVIhDiluOm3wt4GiogXvdJvtk8KRdOsrGwLiZhdTCHn2gIjj6y9FCaQNofXA=,iv:QIZc7UQ2xelaxK77MMJ/n726vEbk3LwL9NvBg+AI37c=,tag:mn/Ypl2pfrrwlsrICwUW9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
