apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5yCvnYx2zYSzITbP+t4=,iv:qHRNhnXGWWCWBRhiL+U03vQd99dV5SXo1pm6zGkOlJI=,tag:ul7WnICnZzNo8GfwQNWFkw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:3oZunZ8kZieRiFIyV8yfBA==,iv:qTGQg8aFtz5KZpcWbz3rTzY5e6JGyw/BlP5hpLlkFMk=,tag:tAsomCEAzfmCc7fgHSI9CA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Wjhw5M02IpUd9cigflOPwUSDQIsbcVuuSX0YQ2/25qSD3r/J,iv:B/no5sYkL7WvfIP9CrqeYv4V94mdoR3SMhHtktn3bwg=,tag:ObTjQscsI7A4Ftq6YQKmMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQWJSeStNRTFiMFZSWXd4
            K2VLR0h3b3hQWmZLM2VIODd1TlNPd3l6dFVBClhwMFlRd3JiSlN5UHEvbHcycVdn
            NDZwL2pGaE9JTHlWbHU0MWxNVnpyanMKLS0tIFBoY0RWVjZKeXJ0NUJvQjRPYzRw
            QnNCbWpza1MzOTlXckZHYmhNVlA1MHMKaQaNn2GTtFiFBbeRuq5eKyExaAFW3Wju
            /kCjtlKk/6WFP02oIPmVZPhJc22nek0WsrcIzv8iRr6cFYGEp7xrlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T20:08:12Z"
    mac: ENC[AES256_GCM,data:ZeIGX+yS0pqlL4fNk8Qhk6XQy9dcH+nwCm42oli7Z2jR/fO8O8Lx5nmDRNjc81VxbGxW44CYqdZ/eeLEMX+De91JT8XoOEmgw/DbWnyjYbMtfMDDwDm0xDh37cCv7kN2XHN6odyArOyOckm9HPGj4FjR1tgcBRPLDxqhhbrwkBQ=,iv:i/VSFZ894OP6TcnZwypZMF1TC4TVGvE7g+LhZrF9HLA=,tag:uSUsGOMSlBG0vB6rV5gpow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
