apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5qSa7GQWIgYO/vliCg1pciQnVsdipRqU4jTT3zt32NE=,iv:VEem/lOlkOCOx8foQrrUBLGKC1STxzGZ+cJ7LPFlw14=,tag:DIka0Y83y+mVW8MqRwev8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZGtnL2YvNk1zZ2lHYXZx
            RlE2M0tHM3lNd2FCNTkrTEEzOFZBTm5nV2w4CmMxMVNzRk1NOGpLWGI5QjczOUt5
            SFFnS0czYUdXMHVjaU1BRHoxWitrekkKLS0tIFhNQitQdE45T3hISnRLd2JKYmtt
            MEpidTlxUEIwZmpZL3AwTHFqTVkwVTgKKtubpuycl5nbHU3tqelg639muaRmqe+1
            6CuBQLA0T164PuGstrnA/ts5chAaT1EEzBWHWVk8V73nHkP6afV0DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T14:33:38Z"
    mac: ENC[AES256_GCM,data:7Nk7On51GWz16hovuNfiXK4VJz6o1wEvVo059IdUeit7lcFFi/lMo20SJvL/tSoIglBL0KqSojs7UcJxDDIrXTGmaPmV6Jn8a4TrNKZzTCf84CaijOT2OdoI63MeHGycfHfQFI4T7UyKdNBCoeyx4DK4V+GolNYb846YJwTw3Dk=,iv:u4hOuWxqI1qAF8fFpEEQJ5I9r/iUdkCzL4UFU2aHyWY=,tag:WS65hBqt6/KcbnJik4wFkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
