apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:YVMjSqs1wMW0+5aOemj7NOiHhdjn2IQ60qz9SxOsRG0=,iv:JGOo8ojJZ/ptPk4eQOaRiOpIGjZjsS45P/VeYHsRHBs=,tag:6J7/vFspaYUN46j+wY1N/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSzlGbFVBYU9YcmxMWW9O
            VSsvbTlBNEo0N08yM1doeVBMM3pJN1FoTUFBCk4yZHRFSDdJWnZQMi9zSEtSUU1I
            MlJxLzNhc0Zvd0R6M3JTeUYrSzZ0bDAKLS0tIFFWeHJUNmdCaFlWNCtkYWFBNWJH
            NzUyOHFVNkE1YnNxMGV6VGNybmozQW8KSrYQZwS5P4qk6jirwVGrtcFdlAlmOJ0B
            M722uSlGOpV1IKGhK9rXK5DVz7Etp/LlvVGVAn2Nr250jFPL04CJVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T18:10:06Z"
    mac: ENC[AES256_GCM,data:7oKf4B2UrqOIDQhCJtKADW4c/3N4ThVo+4OZ2nKdPk7xQDxFjrBwZRlLA5671oHkH2U/DTq15taHchQiA2zc5Dy3U3lvRi7ET7ML39IR+yeVfQBEc4MW92ixzWJW2d5z+sP6C1AtruOCDyMjAcOI367BS4yNxGadtf33gvV0F4E=,iv:OFLuSgRMw902q0K3ESbR+DXvTnG8HnXekkH8yPUC81Q=,tag:KP2O6LZtYyp8XiSA055TGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
