apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:cMcBsXqk8Xf718mgsjrtoUSCdffSNscMihGjDfODZMRsWumjwuxYmg==,iv:znxzFehzyU8qO5WvbwX78JzznrwomXwD3dvHIV6Ezw4=,tag:ShJWCQVr155fNo8WUQFrIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa3RmQ2EwYzhyMm9CbHBy
            b1JqaExRY0VwbWRxRWxNRUg3YVR1MEg0ZjN3Clk4WUJQK3ZOQ1pSWjMremIzZDFV
            T3paNTRqbmEycTYwM04wZEEvN2NVdlUKLS0tIG5XNXlLeFhjUUVVNXZyU3RXT3Rv
            dlcrRE5VdmI2ak8rWlE5R3o2M0JjdG8Kv7IScWsiAcR8zD7+QR6Dsy7PB+w5tcn7
            /IE3xP6Q9CIUzxNFo+Kos9bjnLO6AIjX2ijM1PRIn/vo47xR44lP/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T18:10:06Z"
    mac: ENC[AES256_GCM,data:xDABD9Pz1a96GuV5QZnGPwq2uTbNNaP90X0OKQfqZ54byYpdLcPeK4d8wZJfs19FoPZZSHiMoV3Vb/S3Wc802uglbU/HpqzeuiV1BxHxQ03THQnPJidPqW6zP8u9vSXaS4rfIcWSV32Cg+g3QyGPUNBicoPVsQOQMO7mGCvgiXk=,iv:eVm68cVxv8ibmazwQgC73I+doZTrSl7IvZHsAkRBZGk=,tag:bogFwovCrBYy2LRFd80IIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
