apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:hFjyySIUL9Fed2sgV9o00DoA70kgC95uDkAN9BDdRLGezyFUU9PKAw==,iv:s/AxLG/4SSEYP6hB8eQOtUOhQsQaqfxYW4TCXtidpvM=,tag:VaTpiR6a9CI0fPddWpwG8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdUlkUVhVY3lyeUFUUU9j
            WlFDZ01obW40WExCZ0FDb3UrQk9WTlNRUGtZClBHZzJ3SkhNN01HSEFsTXdjZ1Vi
            RHI2MDF5R1FqZmc0Q3FCTkhDMmoyVmMKLS0tIDlidjIzcUhMMXFVWFRuaDVvRG4x
            V244UHgzdXU1N1dkWXpBWVhLT0RLQ1UKkWUtMnh4qJ8JM99Fq1lDTi4z7FAGmPts
            61Fx4Ep7szxvujRKHPxS26XuZxkkFXIu7AmrZNOHYQoS3jN23Swz7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T19:04:11Z"
    mac: ENC[AES256_GCM,data:vNofVhF1VAE3LVHTvtzEzx9VDpqfRclZ0qhPmOImikTi23StAiCJmDnIQt/Yit8cw3CvyWPBYdJ2oQ/M0krRsq77b1ntYDRnC6TBqCvJ8cC/90v5dIqu97juziJDdJ7ojAB/yzSsD6n0WqNohfdMe5jrsFs+yRKU+hzQYQ6Jw5s=,iv:ri7pEmVIeUKrauDlTQ4uSmPWD4wb+u40pe3GE5Ne34I=,tag:HVO/r11fqpgkH0pLzNAvvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
