apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9gsNfKTPzEgDe98rqeGRQfBNdoEyErQBXit/OJXy7FCkr1hA5IB21w==,iv:1b9xc6f7b18ryqDZm5eHqKcV4MxNS3yuLYuMGNto/2Y=,tag:GvcQ8BHK6mDG9ha8kpJ7CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dntlufq7e24s2ys8esxq8x966re6ht2wuu4mx4nqp5me6w7hg4uqywjwvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dHVNYmpKL3UvTE0wUngy
            MlJKbFdXRWJoQVVmMGFvZk9QcWpPc0hoM3pJCmt1WW4rNEhXam5vVmhGelRON1Nk
            dzkrZ1RrUGswOXQ5WU50RXkzSnE0aGcKLS0tIGgxVTQwTmhOMjl2WklHNGF6NEJ0
            NXJCWXMwR1MwengvT1dmRmo2eVRaTTQKvYFF7gyBT5U9EfbZjSMv4R9kQ2JWpWML
            GwSSQfYmwet3t6gP1fkUMGgPZHAqyUOIPd5KJfDevN71W7JVItEV/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T19:55:04Z"
    mac: ENC[AES256_GCM,data:12mz+hA4/10ZCMppWnYagUOHhnVWOYopGEpX5cm5hgZYkdEhpHgbGSlKO9SXZLoXYAHJAq22F8qr63GFFDxacgekOZXq3MzATHuMb6meXqXXrCag32kF4EVhoNQXgip8IOXDy/wS0bBtf2N09lBK0/c9KzZbx2S3YoMDmSv5938=,iv:1AA+oda6v4XuAR44aUyUfl3Uzmdr33ENwSYdN5ixXHo=,tag:GIZMK0cpkhGGyjmVqGDkyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
